# Generated by Papa's DO-eria
# Customer: Stripe | Order: Data Pipeline
# MODE: DEMO (on-demand resources only)
# Excluded 2 component(s): Redis, MongoDB
#
# NOTE: This code uses BUDGET-FRIENDLY minimal specs for demos.
# Actual sizes are smaller than displayed in-game to reduce costs.
# Edit the 'size' values below for production workloads.
#
# DEPLOY INSTRUCTIONS:
# 1. Save this file as main.tf
# 2. Run: terraform init
# 3. Run: terraform apply -var="do_token=YOUR_TOKEN"
#
# Get your DO token: https://cloud.digitalocean.com/account/api/tokens

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "do_token" {
  description = "DigitalOcean API Token"
  type        = string
  sensitive   = true
}

provider "digitalocean" {
  token = var.do_token
}

resource "digitalocean_droplet" "droplet_cpu_1" {
  image  = "ubuntu-22-04-x64"
  name   = "droplet--cpu--evp56c-1"
  region = "nyc3"
  size   = "c-2"

  tags = ["terraform", "papa-do-eria"]
}

resource "digitalocean_droplet" "droplet_cpu_2" {
  image  = "ubuntu-22-04-x64"
  name   = "droplet--cpu--evp56c-2"
  region = "nyc3"
  size   = "c-2"

  tags = ["terraform", "papa-do-eria"]
}

resource "digitalocean_droplet" "droplet_cpu_3" {
  image  = "ubuntu-22-04-x64"
  name   = "droplet--cpu--evp56c-3"
  region = "nyc3"
  size   = "c-2"

  tags = ["terraform", "papa-do-eria"]
}

resource "digitalocean_volume" "block_storage_1" {
  name                    = "volume-evp56c-1"
  region                  = "nyc3"
  size                    = 10
  initial_filesystem_type = "ext4"
  description             = "Block storage volume"
}

# ============================================
# OUTPUTS - View after 'terraform apply'
# ============================================

output "droplet_ips" {
  description = "Public IP addresses of all droplets"
  value = {
    droplet_cpu_1 = digitalocean_droplet.droplet_cpu_1.ipv4_address
    droplet_cpu_2 = digitalocean_droplet.droplet_cpu_2.ipv4_address
    droplet_cpu_3 = digitalocean_droplet.droplet_cpu_3.ipv4_address
  }
}
