# Generated by Papa's DO-eria
# Customer: Netflix | Order: Static Website with CDN
#
# NOTE: This code uses BUDGET-FRIENDLY minimal specs for demos.
# Actual sizes are smaller than displayed in-game to reduce costs.
# Edit the 'size' values below for production workloads.
#
# DEPLOY INSTRUCTIONS:
# 1. Save this file as main.tf
# 2. Run: terraform init
# 3. Run: terraform apply -var="do_token=YOUR_TOKEN"
#
# Get your DO token: https://cloud.digitalocean.com/account/api/tokens

terraform {
  required_providers {
    digitalocean = {
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }
  }
}

variable "do_token" {
  description = "DigitalOcean API Token"
  type        = string
  sensitive   = true
}

provider "digitalocean" {
  token = var.do_token
}

resource "digitalocean_cdn" "cdn_1" {
  origin = digitalocean_spaces_bucket.spaces_1.bucket_domain_name
  ttl    = 3600
}

resource "digitalocean_floating_ip" "floating_ip_1" {
  region = "nyc3"
}

resource "digitalocean_spaces_bucket" "spaces_1" {
  name   = "bucket-nq6cdc-1"
  region = "nyc3"
  acl    = "private"
}

# ============================================
# OUTPUTS - View after 'terraform apply'
# ============================================

output "spaces_buckets" {
  description = "Spaces bucket endpoints"
  value = {
    spaces_1 = {
      name   = digitalocean_spaces_bucket.spaces_1.name
      urn    = digitalocean_spaces_bucket.spaces_1.urn
      domain = digitalocean_spaces_bucket.spaces_1.bucket_domain_name
    }
  }
}