// lib/terraform-generator.ts
import { PlacedComponent, Order } from "./types";

export function generateTerraformCode(
  placedComponents: PlacedComponent[],
  order: Order | null
): string {
  if (placedComponents.length === 0) {
    return `# Drag components to the build area to generate Terraform code
# Customer: ${order?.customer.name || "Waiting..."}
# Order: ${order?.scenario || "No order yet"}`;
  }

  const lines: string[] = [
    `# Generated by Papa's DO-eria`,
    `# Customer: ${order?.customer.name || "Unknown"}`,
    `# Order: ${order?.scenario || "Custom Build"}`,
    `# Estimated Monthly Cost: $${calculateMonthlyCost(placedComponents)}/mo`,
    "",
    "terraform {",
    "  required_providers {",
    "    digitalocean = {",
    '      source  = "digitalocean/digitalocean"',
    '      version = "~> 2.0"',
    "    }",
    "  }",
    "}",
    "",
    'variable "do_token" {',
    "  description = \"DigitalOcean API Token\"",
    "  type        = string",
    "  sensitive   = true",
    "}",
    "",
    "provider \"digitalocean\" {",
    "  token = var.do_token",
    "}",
    "",
  ];

  // Group components by type and generate resources
  const componentCounts: Record<string, number> = {};

  placedComponents.forEach((placed) => {
    const { component } = placed;
    const type = component.type;

    // Track count for naming
    componentCounts[type] = (componentCounts[type] || 0) + 1;
    const index = componentCounts[type];
    const resourceName = `${type.replace(/-/g, "_")}_${index}`;

    lines.push(...generateResourceBlock(component, resourceName, index));
    lines.push("");
  });

  return lines.join("\n");
}

function generateResourceBlock(
  component: PlacedComponent["component"],
  resourceName: string,
  index: number
): string[] {
  const lines: string[] = [];

  switch (component.type) {
    case "droplet-basic":
    case "droplet-general":
    case "droplet-cpu":
    case "droplet-memory":
      const dropletSize = component.terraformConfig.size as string;
      lines.push(
        `resource "digitalocean_droplet" "${resourceName}" {`,
        `  image  = "ubuntu-22-04-x64"`,
        `  name   = "${component.name.toLowerCase().replace(/[^a-z0-9]/g, "-")}-${index}"`,
        `  region = "nyc3"`,
        `  size   = "${dropletSize}"`,
        "",
        `  tags = ["terraform", "papa-do-eria"]`,
        "}"
      );
      break;

    case "postgres":
      lines.push(
        `resource "digitalocean_database_cluster" "${resourceName}" {`,
        `  name       = "postgres-cluster-${index}"`,
        `  engine     = "pg"`,
        `  version    = "15"`,
        `  size       = "db-s-1vcpu-1gb"`,
        `  region     = "nyc3"`,
        `  node_count = 1`,
        "}"
      );
      break;

    case "mysql":
      lines.push(
        `resource "digitalocean_database_cluster" "${resourceName}" {`,
        `  name       = "mysql-cluster-${index}"`,
        `  engine     = "mysql"`,
        `  version    = "8"`,
        `  size       = "db-s-1vcpu-1gb"`,
        `  region     = "nyc3"`,
        `  node_count = 1`,
        "}"
      );
      break;

    case "redis":
      lines.push(
        `resource "digitalocean_database_cluster" "${resourceName}" {`,
        `  name       = "redis-cluster-${index}"`,
        `  engine     = "redis"`,
        `  version    = "7"`,
        `  size       = "db-s-1vcpu-1gb"`,
        `  region     = "nyc3"`,
        `  node_count = 1`,
        "}"
      );
      break;

    case "mongodb":
      lines.push(
        `resource "digitalocean_database_cluster" "${resourceName}" {`,
        `  name       = "mongodb-cluster-${index}"`,
        `  engine     = "mongodb"`,
        `  version    = "6"`,
        `  size       = "db-s-1vcpu-1gb"`,
        `  region     = "nyc3"`,
        `  node_count = 1`,
        "}"
      );
      break;

    case "load-balancer":
      lines.push(
        `resource "digitalocean_loadbalancer" "${resourceName}" {`,
        `  name   = "lb-${index}"`,
        `  region = "nyc3"`,
        "",
        "  forwarding_rule {",
        "    entry_port     = 443",
        '    entry_protocol = "https"',
        "    target_port    = 80",
        '    target_protocol = "http"',
        "  }",
        "",
        "  healthcheck {",
        "    port     = 80",
        '    protocol = "http"',
        '    path     = "/"',
        "  }",
        "}"
      );
      break;

    case "spaces":
      lines.push(
        `resource "digitalocean_spaces_bucket" "${resourceName}" {`,
        `  name   = "spaces-bucket-${index}"`,
        `  region = "nyc3"`,
        `  acl    = "private"`,
        "}"
      );
      break;

    case "block-storage":
      lines.push(
        `resource "digitalocean_volume" "${resourceName}" {`,
        `  name                    = "volume-${index}"`,
        `  region                  = "nyc3"`,
        `  size                    = 100`,
        `  initial_filesystem_type = "ext4"`,
        `  description             = "Block storage volume"`,
        "}"
      );
      break;

    case "kubernetes":
      lines.push(
        `resource "digitalocean_kubernetes_cluster" "${resourceName}" {`,
        `  name    = "k8s-cluster-${index}"`,
        `  region  = "nyc3"`,
        `  version = "1.28.2-do.0"`,
        "",
        "  node_pool {",
        '    name       = "worker-pool"',
        '    size       = "s-2vcpu-4gb"',
        "    node_count = 3",
        "  }",
        "}"
      );
      break;

    case "container-registry":
      lines.push(
        `resource "digitalocean_container_registry" "${resourceName}" {`,
        `  name                   = "registry-${index}"`,
        `  subscription_tier_slug = "basic"`,
        "}"
      );
      break;

    case "vpc":
      lines.push(
        `resource "digitalocean_vpc" "${resourceName}" {`,
        `  name     = "vpc-${index}"`,
        `  region   = "nyc3"`,
        `  ip_range = "10.10.${index}0.0/24"`,
        "}"
      );
      break;

    case "floating-ip":
      lines.push(
        `resource "digitalocean_floating_ip" "${resourceName}" {`,
        `  region = "nyc3"`,
        "}"
      );
      break;

    case "cdn":
      lines.push(
        `resource "digitalocean_cdn" "${resourceName}" {`,
        `  origin = digitalocean_spaces_bucket.spaces_1.bucket_domain_name`,
        `  ttl    = 3600`,
        "}"
      );
      break;

    case "firewall":
      lines.push(
        `resource "digitalocean_firewall" "${resourceName}" {`,
        `  name = "firewall-${index}"`,
        "",
        "  inbound_rule {",
        '    protocol         = "tcp"',
        '    port_range       = "22"',
        '    source_addresses = ["0.0.0.0/0"]',
        "  }",
        "",
        "  inbound_rule {",
        '    protocol         = "tcp"',
        '    port_range       = "80"',
        '    source_addresses = ["0.0.0.0/0"]',
        "  }",
        "",
        "  inbound_rule {",
        '    protocol         = "tcp"',
        '    port_range       = "443"',
        '    source_addresses = ["0.0.0.0/0"]',
        "  }",
        "",
        "  outbound_rule {",
        '    protocol              = "tcp"',
        '    port_range            = "1-65535"',
        '    destination_addresses = ["0.0.0.0/0"]',
        "  }",
        "}"
      );
      break;

    case "app-platform":
      lines.push(
        `resource "digitalocean_app" "${resourceName}" {`,
        "  spec {",
        `    name   = "app-${index}"`,
        `    region = "nyc"`,
        "",
        "    service {",
        `      name               = "web"`,
        `      instance_count     = 1`,
        `      instance_size_slug = "basic-xxs"`,
        "",
        "      git {",
        '        repo_clone_url = "https://github.com/example/app.git"',
        '        branch         = "main"',
        "      }",
        "    }",
        "  }",
        "}"
      );
      break;

    case "functions":
      lines.push(
        `resource "digitalocean_app" "${resourceName}" {`,
        "  spec {",
        `    name   = "functions-${index}"`,
        `    region = "nyc"`,
        "",
        "    function {",
        `      name       = "fn"`,
        '      source_dir = "/"',
        "",
        "      git {",
        '        repo_clone_url = "https://github.com/example/functions.git"',
        '        branch         = "main"',
        "      }",
        "    }",
        "  }",
        "}"
      );
      break;

    case "monitoring":
      lines.push(
        `resource "digitalocean_monitor_alert" "${resourceName}" {`,
        '  alerts {',
        '    email = ["ops@example.com"]',
        '  }',
        `  window      = "5m"`,
        `  type        = "v1/insights/droplet/cpu"`,
        `  compare     = "GreaterThan"`,
        `  value       = 80`,
        `  enabled     = true`,
        `  description = "High CPU usage alert"`,
        "}"
      );
      break;

    default:
      lines.push(`# Unknown component type: ${component.type}`);
  }

  return lines;
}

export function calculateMonthlyCost(placedComponents: PlacedComponent[]): number {
  return placedComponents.reduce((sum, p) => sum + p.component.monthlyCost, 0);
}
